// Real client configuration — publishable keys only.
// Generated by clerk env pull; never place secret keys here
// (constitution III, research R7).
export const CLERK_PUBLISHABLE_KEY = 'pk_test_Y29oZXJlbnQtaGFsaWJ1dC01OTE5LmNsZXJrLmFjY291bnRzLmRldiQ';
export const SUPABASE_URL = 'https://svzqcfpuifvqvwubmkia.supabase.co';
export const SUPABASE_ANON_KEY = 'sb_publishable_vLvgCOqyKpa5WjrPI9TXtg_rP5X9WgZ';
